# Generated by Django 2.0.5 on 2018-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meassure',
            field=models.CharField(default='gr', max_length=50),
            preserve_default=False,
        ),
    ]
