# Generated by Django 2.0.5 on 2018-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0003_auto_20180530_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../media/harina.jpeg', max_length=50, upload_to=''),
        ),
    ]
